# Generated by Django 3.2.5 on 2021-08-04 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='grupo',
        ),
        migrations.AddField(
            model_name='plate',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.group', verbose_name='Grupo'),
            preserve_default=False,
        ),
    ]
